
FROM tritonserver_builder_image AS build
FROM tritonserver_buildbase
COPY --from=build /tmp/tritonbuild /tmp/tritonbuild

RUN mkdir -p /tmp/tritonbuild/install/third-party-src &&     (cd /tmp/tritonbuild/tritonserver/build &&      tar zcf /tmp/tritonbuild/install/third-party-src/src.tar.gz third-party-src)
COPY --from=build /workspace/build/server/README.third-party-src /tmp/tritonbuild/install/third-party-src/README
